# fly.toml file generated for summer-dew-5128 on 2023-04-02T18:16:04+03:00

app = "summer-dew-5128"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "arn"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
